server:
  port: 70

spring:
  application:
    name: auth-service
  mongodb:
    uri: mongodb+srv://672023116_db_user:pzCCcnuDDe@clusterws.ekjhkmr.mongodb.net/
    database: edu_db

eureka:
  client:
    service-url:
      defaultZone: http://localhost:66/eureka

jwt:
  secret: educonnect-rahasia-super-aman-jangan-disebar-2026
  expiration: 3600000