server:
  port: 8090

spring:
  application:
    name: website-bff

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8079/eureka

jwt:
  secret: educonnect-rahasia-super-aman-jangan-disebar-2026